GET http://localhost:9000/api/blogs

###

POST http://localhost:9000/api/blogs
Content-Type: application/json

{
    "title": "Introducción a Node",
    "author": "Sarah Haus",
    "url": "www.sarahhaus.org",
    "likes": 795
}

