GET http://localhost:9000/api/blogs

###

POST http://localhost:9000/api/blogs
Content-Type: application/json

{
    "title": "HTML & CSS3",
    "author": "Jordi Begues",
    "url": "www.jordibegues.org",
    "likes": 637
}

